package com.scut.mall.test;

import com.scut.mall.test.Address;
import com.scut.mall.test.AddressExample;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    int countByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    int insertSelective(Address record);
}