package com.scut.mall.test;

import com.scut.mall.test.Order;
import com.scut.mall.test.OrderExample;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    int countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    int insertSelective(Order record);
}