package com.scut.mall.test;

import java.io.Serializable;

public class Address implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressID
     *
     */
    private Integer addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.userId
     *
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.province
     *
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.county
     *
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.detailAddr
     *
     */
    private String detailaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.conName
     *
     */
    private String conname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.conTel
     *
     */
    private String contel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressID
     *
     * @return the value of address.addressID
     *
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressID
     *
     * @param addressid the value for address.addressID
     *
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.userId
     *
     * @return the value of address.userId
     *
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.userId
     *
     * @param userid the value for address.userId
     *
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.province
     *
     * @return the value of address.province
     *
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.province
     *
     * @param province the value for address.province
     *
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.county
     *
     * @return the value of address.county
     *
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.county
     *
     * @param county the value for address.county
     *
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.detailAddr
     *
     * @return the value of address.detailAddr
     *
     */
    public String getDetailaddr() {
        return detailaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.detailAddr
     *
     * @param detailaddr the value for address.detailAddr
     *
     */
    public void setDetailaddr(String detailaddr) {
        this.detailaddr = detailaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.conName
     *
     * @return the value of address.conName
     *
     */
    public String getConname() {
        return conname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.conName
     *
     * @param conname the value for address.conName
     *
     */
    public void setConname(String conname) {
        this.conname = conname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.conTel
     *
     * @return the value of address.conTel
     *
     */
    public String getContel() {
        return contel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.conTel
     *
     * @param contel the value for address.conTel
     *
     */
    public void setContel(String contel) {
        this.contel = contel;
    }
}