package com.scut.mall.test;

import com.scut.mall.test.Product;
import com.scut.mall.test.ProductExample;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    int countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    int insertSelective(Product record);
}