package com.scut.mall.test;

import java.io.Serializable;

public class ProductWithBLOBs extends Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.remark
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.xremark
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    private String xremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.remark
     *
     * @return the value of product.remark
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.remark
     *
     * @param remark the value for product.remark
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.xremark
     *
     * @return the value of product.xremark
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public String getXremark() {
        return xremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.xremark
     *
     * @param xremark the value for product.xremark
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public void setXremark(String xremark) {
        this.xremark = xremark;
    }
}