package com.scut.mall.test;

import java.io.Serializable;

public class ProductCategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.id
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.cname
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.parent_id
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.type
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_category
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.id
     *
     * @return the value of product_category.id
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.id
     *
     * @param id the value for product_category.id
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.cname
     *
     * @return the value of product_category.cname
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.cname
     *
     * @param cname the value for product_category.cname
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.parent_id
     *
     * @return the value of product_category.parent_id
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.parent_id
     *
     * @param parentId the value for product_category.parent_id
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.type
     *
     * @return the value of product_category.type
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.type
     *
     * @param type the value for product_category.type
     *
     * @mbggenerated Sun Mar 08 18:37:02 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }
}